powered_by:         runs on
abstract:           Einleitung
download:           PDF
share:              Teilen
date_publication:   Veröffentlicht
keywords:           Keywords
cite_as:            Zitiervorschlag
quote_open:         "&bdquo;"
quote_close:        "&ldquo;"
downloadData:       Primärdaten herunterladen
toc:                Inhalt
toc_long:           Inhaltsübersicht
questions:          Fragen oder Anregungen?
write_mail:         Schreibe eine Mail mit Feedback an
read_on:            Gesamte Studie lesen
cited_source:       Zitierte Quelle
authors:            Autorinnen
visit_website:      Website besuchen
