lang:                   en
styles:                 theme/styles/sample-journal.css
scripts:                theme/scripts/lrnlab.js
brand:                  graphite by impact·distillery
background_url:         theme/images/background.jpg
short_url:              https://idist.io/g/lrnlab-agile-en
social_image_url:       https://idist.io/g/lrnlab-agile-en/assets/images/social.png
title:                  "Rethinking academic publications"
subtitle:               "Developing an open-source-framework for a multi-layer narrative in online publishing"
authors:                Marcel Hebing, Larissa Wunderlich, Julia Ebert
year:                   2017
cite_as:                "Hebing, M., Wunderlich, L., & Ebert, J. (2017). Rethinking Academic Publications: Developing an open-source- framework for a multi-layer narrative in online publishing. xCoAx Proceedings of the conference on Computation, Communication, Aesthetics & X, 2017, 29–36."
date_publication:       Oct 2017
date_submission:
date_last_updated:
logo_url:
pdf_url:                http://2017.xcoax.org/xCoAx2017.pdf
isbn:                   978-989-746-128-6
doi:
contact_email:          mhebing@diw.de
data_usage:
disclaimer:
author_info:            Graphite – enhanced publications for a digital environment
author_info_sticky:     true
keywords:               scientific publications, multi-layered publishing, cross-media publications, data visualisation, open science, science communication, knowledge access, knowledge design, usability, technical interoperability
terms_of_use:
imprint:
licence:
abstract:               "The internet has fundamentally changed the way researchers work and collaborate, but has had less impact on the way they publish their results. In this paper, we ask how scientific reports should be designed with the internet as the primary distribution channel in mind. We propose a concept for a multi-layer design, which is capable of including both interactive elements and a comprehensive data-layer. For the implementation, we suggest working with an output-independent format and a modular compiler to generate various output formats, most of all, HTML and PDF. The HTML-version utilizes modern web standards like HTML5, CSS3 and JavaScript. This enables us, for example, to include interactive visualizations, raw datasets, or syntax files directly in- to a publication. The redesign also raises more general questions of how articles are used to facilitate scientific communication, concerning, for example, the way we cite previous work or the concept of scientific authorship in general."
:---------------------------------------------------:
tabs:
  - title: "Article"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
  - title: "Authors"
    ref: "/editors/"
    slug: editors
    md_container: section
  - title: "Executive Summary"
    ref: "/summary/"
    slug: summary
    md_container: section
  - title: "Sources"
    ref: "/directories/"
    slug: directories
    md_container: section
  - title: "Imprint"
    ref: "/imprint/"
    slug: imprint
    md_container: section
