brand:                  graphite by impact·distillery
background_url:         images/background.jpg
title:                  Agilität – ein neues Buzzword, oder lebensnotwendige Fähigkeit für Organisationen im digitalen Zeitalter?
subtitle:               Learn. Match. Partner.
authors:                Andrea Kahlenberg, Jumana Klotsch und Jenny Fadranski 
year:                   2018
cite_as:                "Kahlenberg, A., Klotsch, J., Fadranski, J. (2018) Agilität Neues Buzzword, oder lebensnotwendige Fähigkeit für Organisationen im digitalen Zeitalter? Whitepaper des LRN LAB by innogy Consulting."
date_publication:       Februar 2018
date_submission:
date_last_updated:
logo_url:
pdf_url:
doi:
contact_email:
data_usage:
disclaimer:
author_info:
author_info_sticky:
keywords:
terms_of_use:
imprint:
licence:
abstract:
tabs:
  - title: "Gesamte Studie"
    ref: "/"
    slug: index
    include_abstract: true
    md_container: article
